run:
  timeout: 5m
  tests: true
  issues-exit-code: 1

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - unused
