# golangci-lint configuration
run:
  timeout: 10m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0