name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        
        Please search existing issues before creating a new one.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure provider with...
        2. Create resource...
        3. Run terraform apply...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Terraform Configuration
      description: Please provide your Terraform configuration (remove sensitive data)
      render: hcl
      placeholder: |
        provider "redisacl" {
          # Your configuration
        }
        
        resource "redisacl_user" "example" {
          # Your resource configuration
        }
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages and Logs
      description: Please provide any error messages or relevant log output
      render: shell
      placeholder: Paste error messages and logs here...

  - type: input
    id: terraform-version
    attributes:
      label: Terraform Version
      description: What version of Terraform are you using?
      placeholder: "1.6.0"
    validations:
      required: true

  - type: input
    id: provider-version
    attributes:
      label: Provider Version
      description: What version of the Redis ACL provider are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: redis-version
    attributes:
      label: Redis Version
      description: What version of Redis are you using?
      placeholder: "7.0.0"
    validations:
      required: true

  - type: dropdown
    id: redis-deployment
    attributes:
      label: Redis Deployment Type
      description: What type of Redis deployment are you using?
      options:
        - Standalone
        - Sentinel
        - Cluster
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "Ubuntu 22.04, macOS 13.0, Windows 11, etc."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true