name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! 
        
        Please search existing issues and discussions before creating a new feature request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Resource
        - New Data Source
        - Provider Configuration
        - Resource Enhancement
        - Data Source Enhancement
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature.
      placeholder: |
        I need this feature because...
        
        My workflow involves...
        
        This would help me...
    validations:
      required: true

  - type: textarea
    id: example-config
    attributes:
      label: Example Configuration
      description: If applicable, provide an example of how you'd like to use this feature.
      render: hcl
      placeholder: |
        # Example of how the feature might work
        resource "redisacl_new_resource" "example" {
          # Configuration here
        }

  - type: textarea
    id: redis-context
    attributes:
      label: Redis Context
      description: How does this relate to Redis ACL functionality?
      placeholder: |
        This feature would help manage Redis ACL...
        
        The Redis command equivalent would be...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to implement this feature and submit a PR
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true